### ISSUE TITLE
咨询：关于视频缓存的问题

### ISSUE THREAD

**Issue by Chand-zhang** [ksvc/KSYMediaPlayer_Android#111]
你好，咨询个视频缓存的问题。
直播场景，为了保证直播观看的连续性我关闭了直播追赶，也就是setBufferTimeMax设置为0.0f。
在播放中执行暂停，视频数据会缓存到哪里？内存还是磁盘？

**Comment by FirmianaRain** [comment]
内存

**Comment by Chand-zhang** [comment]
好的，多谢。
内存的话，需要考虑必须加缓存时间了。
