### ISSUE TITLE
部分手机崩溃

### ISSUE THREAD

**Issue by a544393709** [ksvc/KSYMediaPlayer_Android#112]
请教下这个问题怎么解决呢
#838 java.lang.IllegalArgumentException
you must call setOutFormat
com.ksyun.media.streamer.filter.audio.AudioResampleFilter.doFormatChanged(AudioResampleFilter.java:43)

**Comment by FirmianaRain** [comment]
这个问题是推流的，请看 https://github.com/ksvc/KSYStreamer_Android
