### ISSUE TITLE
是否可以控制播放的带宽

### ISSUE THREAD

**Issue by lichens1** [ksvc/KSYMediaPlayer_Android#113]
如果使用该播放器同时进行多路视屏流的播放 , (比如一路1080p的和多路720p的视屏流)是否可以将1080p的一路设置网络优先级高 , 现在的情况是同时播放1080p的会有卡顿 , 720p的不会卡

**Comment by fpzeng** [comment]
如果单独播放1080p的话，卡顿吗？
这个和你当前网络的下行带宽有关的
