### ISSUE TITLE
在每次播放完视频之后就会报错闪退，报错信息好像是说没有开启硬件加速 但是开启硬件加速之后还是一样

### ISSUE THREAD

**Issue by CoderTung** [ksvc/KSYMediaPlayer_Android#115]
java.lang.RuntimeException: Error during detachFromGLContext
`at android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:195) `
` at android.view.TextureView.destroySurface(TextureView.java:232) `
` at android.view.TextureView.destroyHardwareResources(TextureView.java:344) `
`at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2293)`
`at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2300)`

**Comment by FirmianaRain** [comment]
似乎没看到SDK的相关包名，请问你怎么使用的TextureView呢？
