### ISSUE TITLE
m3u8 播放錯誤

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYMediaPlayer_Android#125]
Log 如下：
05-09 13:15:48.933 20108-20108/com.drfame.android E/com.ksyun.media.player.KSYMediaPlayer: Error (-1004,206)
05-09 13:15:48.953 20108-20108/com.drfame.android E/ViewerFragment: OnErrorListener, Error:-1004,extra:206
                                                                    
                                                                    [ 05-09 13:15:48.963 20108:20789 W/         ]
                                                                    Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
05-09 13:15:48.963 20108-20789/com.drfame.android W/art: Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error

**Comment by FirmianaRain** [comment]
请问是开播失败呢还是在播放过程中出的问题？
可以看下此Wiki: https://github.com/ksvc/KSYMediaPlayer_Android/wiki/timeout

**Comment by bingdow** [comment]
@FirmianaRain 開播就失敗了，調用 setTimeout 依然無效

**Comment by bingdow** [comment]
@FirmianaRain 發現靜態影片(非即時推播)會出現這錯誤，但正常推播不會。

**Comment by FirmianaRain** [comment]
是本地的m3u8？
请问ts切片和m3u8的都在同一个目录吗？

**Comment by bingdow** [comment]
@FirmianaRain 不知道呢，都不是自己維護的影片，我試了以下這幾個都不行
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8
http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8
http://www.streambox.fr/playlists/test_001/stream.m3u8

**Comment by bingdow** [comment]
@FirmianaRain 另外我發現 hls 視頻套用 VIDEO_SCALING_MODE_SCALE_TO_FIT 無效，至於 rtmp 沒什麼問題。

**Comment by FirmianaRain** [comment]
1. 这些m3u8里都含有多个码流，播放SDK暂不支持
2. VIDEO_SCALING_MODE_SCALE_TO_FIT与视频是什么封装形式无关

hls视频的宽高比例与手机屏幕宽高比例一样的话，不论采用何种scaling mode，渲染的效果都是一样的

**Comment by bingdow** [comment]
@FirmianaRain VIDEO_SCALING_MODE_SCALE_TO_FIT 的問題我在說清楚點，就是推流視頻是 width > height 的，觀看端手機一直保持縱向模式，我發現如果是 rtmp 流則觀看端畫面比例正常。
但如果是 hls 則畫面被拉伸 (stretched) 到全螢幕了，比例錯誤。

**Comment by FirmianaRain** [comment]
应该不会出现类似的问题，麻烦确认下在播放rtmp和hls时使用相同的scalingMode吗

**Comment by bingdow** [comment]
@FirmianaRain OK 我發現畫面比例拉伸問題，在軟編模式不會出現，自動或硬解則會。

**Comment by FirmianaRain** [comment]
硬解使用KSYTextureView，请见wiki： https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KSYTextureView
