### ISSUE TITLE
錯誤碼 10009 是什麼？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYMediaPlayer_Android#126]
Log 如下：
`05-15 16:22:03.143 25778-25778/com.myApp.android E/ViewerFragment: OnErrorListener, Error:-10009,extra:416`

**Comment by FirmianaRain** [comment]
http请求返回错误码 4xx，对于你的问题，返回的错误码是416
具体的错误码定义可见wiki：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KsyMediaPlayerConstants
