### ISSUE TITLE
http-flv 有追趕功能嗎？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYMediaPlayer_Android#132]
服務端採 pseudo-streaming(progressive downloading) 請問播放 http-flv 有追趕功能嗎？

**Comment by bingdow** [comment]
另一個問題是，如果 http-flv 發生 buffering 結束後有辦法跳到最新一禎嗎？

**Comment by fpzeng** [comment]
我们支持http-flv的追赶功能，请阅读[bufferTimeMax延时控制wiki](https://github.com/ksvc/KSYMediaPlayer_Android/wiki/bufferTimeMax0
