### ISSUE TITLE
huawei P9 crash

### ISSUE THREAD

**Issue by zldada** [ksvc/KSYMediaPlayer_Android#134]
here is the log of crash before entering the demo app.

06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xb7
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]     string: '������-44100.pcm'
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]     in call to NewStringUTF
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]     from java.lang.String[] java.io.File.listImpl(java.lang.String)
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410] "Thread-1736" prio=5 tid=17 Runnable
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x12ee6f40 self=0x7f951d1000
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=24523 nice=0 cgrp=top_visible sched=0/0 handle=0x7f7d5c2440
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 213720 50960 1 ) utm=0 stm=0 core=4 HZ=100
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   | stack=0x7f7d4c0000-0x7f7d4c2000 stackSize=1037KB
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 000000000049063c  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+236)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 000000000045f630  /system/lib64/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+220)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0000000000310eec  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1000)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 00000000003117a4  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+116)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 0000000000144ddc  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+144)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 000000000014d010  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.116+11084)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 0000000000156258  /system/lib64/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+468)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00000000000200c0  /system/lib64/libjavacore.so (_Z13toStringArrayI13VectorCounter12VectorGetterEP13_jobjectArrayP7_JNIEnvPT_PT0_+204)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 0000000000020390  /system/lib64/libjavacore.so (???)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 0000000000042ed4  /data/dalvik-cache/arm64/system@framework@boot.oat (Java_java_io_File_listImpl__Ljava_lang_String_2+152)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at java.io.File.listImpl(Native method)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at java.io.File.list(File.java:743)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at java.io.File.listFiles(File.java:785)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at java.io.File.listFiles(File.java:820)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at com.ksyun.player.demo.model.GetList$1.run(GetList.java:30)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:833)
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410] 
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/runtime.cc:368] Runtime aborting...
06-12 11:17:38.985 24498-24523/? A/art: art/runtime/runtime.cc:368]

**Comment by FirmianaRain** [comment]
It seems that some file's name contain illegal character, such as:
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xb7
06-12 11:17:38.984 24498-24523/? A/art: art/runtime/java_vm_ext.cc:410] string: '������-44100.pcm'

**Comment by zldada** [comment]
@FirmianaRain it is a native crash,I just compile the project,and run the demo apk and a crash happening.

**Comment by FirmianaRain** [comment]
This file '������-44100.pcm' contains some characters which can't be parsed as UTF-8.
And it cause system crashed when  NewStringUTF was called.

**Comment by zldada** [comment]
@FirmianaRain Other type of Android Phone like Samsung note 5 and Meizu m3 do not hava such a problem.

**Comment by FirmianaRain** [comment]
Because other android phone like Samsung note 5 and Meizu m3 do not have the file '������-44100.pcm'

**Comment by zldada** [comment]
@FirmianaRain  Your explanation is convincing.  O(∩_∩)O~
