### ISSUE TITLE
播放Flv格式视频时，无法Seek

### ISSUE THREAD

**Issue by scofield-hello** [ksvc/KSYMediaPlayer_Android#157]
在点播Flv视频的时候，seek到指定位置时无法继续播放，onSeekComplete回调之后，Error也会回调，返回码 what=1004, extra= 0， 等待过程中onBufferingUpdate没有回调；

**Comment by FirmianaRain** [comment]
什么flv视频？metadata里有关键帧的信息吗

**Comment by scofield-hello** [comment]
视频地址：http://111.1.56.149/UploadFile/video/ec6049a6-56cc-4cfd-bc74-12f49f0ebbf3.flv
对这块我不是很熟悉，用什么去看metadata

**Comment by FirmianaRain** [comment]
我把视频下载下来上传值ks3，地址如下
https://ks3-cn-beijing.ksyun.com/mobile/ec6049a6-56cc-4cfd-bc74-12f49f0ebbf3.flv
我这能正常seek

**Comment by scofield-hello** [comment]
是上传到多媒体服务器就可以用了吗？我这边不是多媒体服务器，您能否告诉我无法Seek是否是我这边服务器的原因 ？

**Comment by FirmianaRain** [comment]
跟是不是多媒体服务器没啥关系吧
seek实际就是range请求，这个问题你得看下你们的服务器了
