### ISSUE TITLE
setBufferTimeMax问题

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYMediaPlayer_Android#16]
这里说的是　延迟跟整个链路和两端的设备状态都有关，请检查您的设备和网络，如果是公开流请确认播放器的开始播放缓冲区数值设置为0。

而demo设置的为5，那这个是设置为什么值合适呢，这个值的意义和影响是什么呢？

**Comment by FirmianaRain** [comment]
1. 只在直播时生效
2. 设置播放器缓存时长的最大值，当播放器缓存的时长超过该阈值时，会引发播放器追赶，减少主播和观众之间的延迟
3. demo设置为5是为了抗抖动，这个值设置的越小，主播和观众的延迟也越小，对网络越敏感
4. 设置为0表示你放弃直播追赶功能，主播和观众间的延迟不确定

**Comment by Goach** [comment]
好的，谢谢你的回答
