### ISSUE TITLE
为什么金山云点播库在 多码率hls的m3u8列表前面不能播放

### ISSUE THREAD

**Issue by zllikey** [ksvc/KSYMediaPlayer_Android#163]
给个连接你试试 http://120.87.4.70/PLTV/88888894/224/3221225487/index.m3u8
类似下面得播放列表，现在情况是流量在走，就是播放不了，然后触发超时错误1004
这种列表下面得m3u8连接才是真正得播放连接，希望能解决
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1488,BANDWIDTH=4448080
1.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1488,BANDWIDTH=1986633
2.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1488,BANDWIDTH=1165449
3.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1488,BANDWIDTH=652736
4.m3u8

**Comment by FirmianaRain** [comment]
暂不支持多码率的播放

**Comment by zllikey** [comment]
卧槽，那什么时候支持？如果是基于ijkplayer源码，ijk是可以播放这种多码率播放得

**Comment by FirmianaRain** [comment]
我们会尽快安排研发的
