### ISSUE TITLE
播放视频将缩放模式设置为KSYMediaPlayer.VIDEO_SCALING_MODE_NOSCALE_TO_FIT的时候，点击屏幕，画面缩放到四分之一左右，并且跑到左上角

### ISSUE THREAD

**Issue by tribbianiwang** [ksvc/KSYMediaPlayer_Android#170]
播放视频将缩放模式设置为KSYMediaPlayer.VIDEO_SCALING_MODE_NOSCALE_TO_FIT的时候，点击屏幕，画面缩放到四分之一左右，并且跑到左上角

**Comment by fpzeng** [comment]
请问描述的现象是在播放demo里面的表现吗？

**Comment by dengchu817** [comment]
这个问题已经解决，会在下个版本更新

**Comment by FirmianaRain** [comment]
@tribbianiwang 
https://github.com/ksvc/KSYMediaPlayer_Android/releases/tag/v2.0.4

**Comment by tribbianiwang** [comment]
@FirmianaRain 完美解决
