### ISSUE TITLE
能否提供一个支持rtsp协议的版本？还要旧版的实时性延迟比较高，希望有改善

### ISSUE THREAD

**Issue by roger66** [ksvc/KSYMediaPlayer_Android#19]

**Comment by FirmianaRain** [comment]
支持rtsp的版本很快就能提供
**旧版的延迟高**  请问是指那个版本？延迟大概多久？设置的缓存阈值是多少？

**Comment by roger66** [comment]
缓存是0，在有些h264编码的http协议视频延迟就更加高

**Comment by FirmianaRain** [comment]
**缓存是0** 是指调用setBufferTimeMax 设置的值为0吗？
这会关闭直播追赶功能，主播和观众之间的延迟就不可控

**Comment by roger66** [comment]
是setBufferSize

**Comment by FirmianaRain** [comment]
那请问你们有调用setBufferTimeMax这个方法吗？

**Comment by roger66** [comment]
有啊 值为1

**Comment by FirmianaRain** [comment]
请问你们播放什么视频出现延迟比较大的情况？rtmp or http+flv？
可否提供一个播放地址

**Comment by roger66** [comment]
地址是运动相机的 rtsp和http

**Comment by FirmianaRain** [comment]
已release的Android版本不支持rtsp
请问是用http+flv的方案吗？能否给个播放地址？用flash播放器延迟多少？
