### ISSUE TITLE
KSYTextureView播放过程中调用setSpeed无效

### ISSUE THREAD

**Issue by piratewb** [ksvc/KSYMediaPlayer_Android#190]
根据文档描述2.0.2后版本支持，播放过程中修改播放速度，实际使用过程中发现设置速度无效，视频始终以正常速度播放，getSpeed获取到的是设置后的速度，getVersion返回2.0.5
mVideoView.setSpeed(0.1f);
mVideoView.prepareAsync();

**Comment by dengchu817** [comment]
有视频地址吗

**Comment by piratewb** [comment]
sorry，可能是视频源的问题，设置不同速度帧率调的很厉害，看不出速度变化
