### ISSUE TITLE
HostnameVerifier 不安全的问题

### ISSUE THREAD

**Issue by pavkoo** [ksvc/KSYMediaPlayer_Android#195]
参考链接：https://support.google.com/faqs/answer/7188426
请修改com.ksyun.media.player.https.KsyHttpConnection类。并增加一个开发接口让开发者可以自己设置安全规则

**Comment by FirmianaRain** [comment]
请更新版本

**Comment by pavkoo** [comment]
新版本已经修复了v2.1.0
