### ISSUE TITLE
希望支持切换音轨

### ISSUE THREAD

**Issue by xwlcn** [ksvc/KSYMediaPlayer_Android#198]
不知道目前SDK支不支持切换音轨，如果没有的话希望后续版本支持切换音轨。

**Comment by FirmianaRain** [comment]
SDK是支持多音轨切换，可以参考下面的wiki
https://github.com/ksvc/KSYMediaPlayer_Android/wiki/selectTrack

**Comment by xwlcn** [comment]
Nice. 之前用过很多功能都不支持，目前完善了不少，谢谢了。
