### ISSUE TITLE
切换音轨BUG

### ISSUE THREAD

**Issue by xwlcn** [ksvc/KSYMediaPlayer_Android#203]
每次切换音轨，播放器自动快进几十秒，而且并不是直接 seekTo 那种效果，是时间轴直接跳到后几十秒，然后以倍速播放到那个位置。还有就是 getLanguage 貌似只能取到前三个字符。

**Comment by FirmianaRain** [comment]
OK. 我们会看下这个问题

**Comment by FirmianaRain** [comment]
@xwlcn 问题已经找到，预计下个版本解决这个问题

**Comment by xwlcn** [comment]
好的。

**Comment by ghost** [comment]
请问解决了吗，我现在用的最新版点播sdk还是有这个问题
