### ISSUE TITLE
怎么设置回调 onSurfaceTextureDestroyed ？

### ISSUE THREAD

**Issue by cyigo** [ksvc/KSYMediaPlayer_Android#224]
怎么设置回调 onSurfaceTextureDestroyed ？
或者有什么其他办法

**Comment by dengchu817** [comment]
是设置KSYTextureView的onSurfaceTextureDestroyed 回调吗

**Comment by FirmianaRain** [comment]
这个是KSYTextureView的开源代码：https://github.com/ksvc/KSYMediaPlayer_Android/tree/master/src

可以根据自身需求做修改

**Comment by cyigo** [comment]
@dengchu817   是的，因为要改造我们app以前的代码，需要用这个回调

**Comment by cyigo** [comment]
@FirmianaRain   哦，只能自己改是吧？

**Comment by FirmianaRain** [comment]
@cyigo 是的，KSYTextureView实际是对KSYMediaPlayer和TextureView的封装，现在开源的代码跟线上的KSYTextureView代码是一致的，可以根据自身需求做开发

**Comment by cyigo** [comment]
@FirmianaRain   好的  谢谢
