### ISSUE TITLE
直接闪退了

### ISSUE THREAD

**Issue by hegelsu** [ksvc/KSYMediaPlayer_Android#228]
01-24 23:20:48.777 I/KSYMediaPlayer( 8067): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
01-24 23:20:48.781 I/KSYMediaPlayer( 8067): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
01-24 23:20:48.785 I/KSYMediaPlayer( 8067): [zzy][a]SDL_Android_AudioTrack_new_from_spec: audio track buffer size:13372
01-24 23:20:48.785 I/KSYMediaPlayer( 8067): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
01-24 23:20:48.785 I/KSYMediaPlayer( 8067): [zzy][a]aout_open_audio_n, buffer_size:13372 
01-24 23:20:48.785 I/KSYMediaPlayer( 8067): audio_session_id = 50
01-24 23:20:48.785 D/com.ksyun.media.player.KSYMediaPlayer( 8067): KSYMediaPlayer Use Software Decode and SDK Version is:2.2.0, BufferTimeMax:2.0
01-24 23:20:48.901 I/KSYMediaPlayer( 8067): init filter w3fdif
01-24 23:20:48.901 D/KSYMediaPlayer( 8067): SDL_VoutFFmpeg_CreateOverlay(w=480, h=288, fmt=I420(0x30323449, dp=0xb882de28)
01-24 23:20:48.901 D/KSYMediaPlayer( 8067): Video: first frame decoded
01-24 23:20:48.901 D/KSYMediaPlayer( 8067): SDL_VoutFFmpeg_CreateOverlay(w=480, h=288, fmt=I420(0x30323449, dp=0xb882de28)
01-24 23:20:48.905 D/KSYMediaPlayer( 8067): SDL_VoutFFmpeg_CreateOverlay(w=480, h=288, fmt=I420(0x30323449, dp=0xb882de28)
01-24 23:20:48.905 I/KSYMediaPlayer( 8067): [EGL] eglInitialize 1.4
01-24 23:20:48.905 D/        ( 8067): HostConnection::get() New Host Connection established 0xb8bf84e8, tid 8215
01-24 23:20:48.909 I/KSYMediaPlayer( 8067): [EGL] ANativeWindow_setBuffersGeometry(f=1);
01-24 23:20:48.925 I/KSYMediaPlayer( 8067): [GLES2] Version = OpenGL ES 2.0 (4.5.0 - Build 23.20.16.4877)
01-24 23:20:48.925 I/KSYMediaPlayer( 8067): [GLES2] Vendor = Google (Intel)
01-24 23:20:48.925 I/KSYMediaPlayer( 8067): [GLES2] Renderer = OpenGL ES Translator (Intel(R) HD Graphics 630)
01-24 23:20:48.925 I/KSYMediaPlayer( 8067): [GLES2] Extensions = GL_EXT_debug_marker GL_OES_EGL_image GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_texture_float GL_OES_texture_float_linear GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_packed_depth_stencil GL_OES_vertex_half_float 
01-24 23:20:48.925 I/KSYMediaPlayer( 8067): create render yuv420p
01-24 23:20:48.937 I/KSYMediaPlayer( 8067): use render yuv420p
01-24 23:20:48.941 I/KSYMediaPlayer( 8067): [yuv420p] padding changed: 512 - 480 = 32 (0.062500)
01-24 23:20:48.953 F//system/bin/app_process( 8067): stack corruption detected: aborted

如果我把sdk换成2.1.0的就没问题，升到最新一播放就app挂掉

**Comment by FirmianaRain** [comment]
这不是崩溃日志，有其他的日志吗？
jar和动态库同时更新了吗

**Comment by hegelsu** [comment]
库肯定同时更新了的，用的vod的库，其实换live的也是一样的错，还能如何给你更详细的Log

**Comment by FirmianaRain** [comment]
jar包更新了吗

**Comment by hegelsu** [comment]
我是直接复制的https://github.com/ksvc/KSYMediaPlayer_Android/archive/v2.2.0.zip
然后jar和lib都覆盖本地的测试的，2.1.0之后的版本都抱同样的错，我的环境是Xamarin绑定后使用的

**Comment by dengchu817** [comment]
@hegelsu 崩溃日志有吗？根据你的描述我看了一下，2.1.1并没有什么大的改动，2.1.2进行了Gradle和NDK版本的升级

**Comment by hegelsu** [comment]
[Temp.zip](https://github.com/ksvc/KSYMediaPlayer_Android/files/1662459/Temp.zip)
你看这个对你们分析有用么

**Comment by dengchu817** [comment]
你的这个文件怎么打开，你就发一下崩溃堆栈的文本日志

**Comment by hegelsu** [comment]
这个应该是你们的sdk生成的吧，我再找找还有没有其它日志

**Comment by dengchu817** [comment]
播放器没有在本地生成日志，你的IDE上的崩溃堆栈就行啊

**Comment by hegelsu** [comment]
我的IDE是Visual Studio，调试日志也就是最开始发的，不是as也不是eclipse

**Comment by hegelsu** [comment]
更新至2.2.2之后，崩溃问题得到解决。
