### ISSUE TITLE
5.1手机CRASH：JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8

### ISSUE THREAD

**Issue by sharememories** [ksvc/KSYMediaPlayer_Android#236]
播放这个视频的时候CRASH：https://out-20180107225302163-pv8uln5kxq.oss-cn-shanghai.aliyuncs.com/sv/24a1e4fb-161367cf434/24a1e4fb-161367cf434.mp4

02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0xcc
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]     string: '����'
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65] "Thread-119251" prio=5 tid=102 Runnable
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x42d0c0a0 self=0xac0de810
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   | sysTid=30165 nice=0 cgrp=default sched=0/0 handle=0xac0daf78
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 2709846 9099269 27 ) utm=0 stm=0 core=4 HZ=100
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   | stack=0x87efc000-0x87efe000 stackSize=1012KB
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #00 pc 00004864  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00003031  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #02 pc 00253c69  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #03 pc 00235249  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+144)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000b13fb  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b1b41  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b3fcb  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.129)+882)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000bca49  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+36)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #08 pc 000c79ab  /data/app/com.yaya.-2/lib/arm/libksyplayer.so (J4AC_android_os_Bundle__putString__withCString+62)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #09 pc 000a9fbf  /data/app/com.yaya.-2/lib/arm/libksyplayer.so (???)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #10 pc 000bd4d5  /data/app/com.yaya.-2/lib/arm/libksyplayer.so (???)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #11 pc 0001349b  /system/lib/libc.so (__pthread_start(void*)+30)
02-06 14:38:09.227 29052-30165/com.yaya.A/art: art/runtime/check_jni.cc:65]   native: #12 pc 0001149f  /system/lib/libc.so (__start_thread+6)

**Comment by sharememories** [comment]
补充一下： 把jar文件和so文件换回老版本就是好的，最新版本的库有问题

**Comment by dengchu817** [comment]
@sharememories 这个问题我们定位到了，会尽快修复的

**Comment by sharememories** [comment]
好的，感谢！我们项目现在用的是Demo里的版本，会有问题吗？

**Comment by dengchu817** [comment]
2.2.1会有这个问题，之前的版本没问题

**Comment by FirmianaRain** [comment]
新版本 v2.2.2已经fix这个问题

**Comment by sharememories** [comment]
thx
