### ISSUE TITLE
播放黑屏

### ISSUE THREAD

**Issue by rcwind** [ksvc/KSYMediaPlayer_Android#27]
播放时先stop掉，再setDataSource播放，有声音，没图像，即使重新初始化KSYMediaPlayer也是黑屏，跟surfaceview有关吗

**Comment by FirmianaRain** [comment]
有设置新的Surface或者SurfaceHolder给播放器吗？

**Comment by rcwind** [comment]
是这样，VideoPlayerView继承SurfaceView，KSYMediaPlayer是其成员，如果stop了，再start就调用initView
private void initView() {

        initPlayer();
        setKeepScreenOn(true);

        SurfaceHolder mSurfaceHolder = getHolder();
        mSurfaceHolder.removeCallback(mSurfaceCallback);
        mSurfaceHolder.addCallback(mSurfaceCallback = new SurfaceHolder.Callback() {
            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                if(ksyMediaPlayer != null && ksyMediaPlayer.isPlaying())
                    ksyMediaPlayer.setVideoScalingMode(KSYMediaPlayer.VIDEO_SCALING_MODE_SCALE_TO_FIT);

                if(ksyMediaPlayer != null) {
                    final Surface newSurface = holder.getSurface();
                    ksyMediaPlayer.setDisplay(holder);
                    if (mSurface != newSurface) {
                        mSurface = newSurface;
                        ksyMediaPlayer.setSurface(mSurface);
                    }
                }
            }

            @Override
            public void surfaceCreated(SurfaceHolder holder) {
                if(ksyMediaPlayer != null) {
                    final Surface newSurface = holder.getSurface();
                    ksyMediaPlayer.setDisplay(holder);
                    if (mSurface != newSurface) {
                        mSurface = newSurface;
                        ksyMediaPlayer.setSurface(mSurface);
                    }
                }
            }

            @Override
            public void surfaceDestroyed(SurfaceHolder holder) {
                if(ksyMediaPlayer != null) {
                    ksyMediaPlayer.setDisplay(null);
                    mSurface = null;
                }
            }
        });
    }

**Comment by FirmianaRain** [comment]
removeCallback之后，addCallback新加的callbak有被调用过吗
