### ISSUE TITLE
Android6.0 截屏ksyMediaPlayer.getScreenShot黑屏，6.0以下版本是好的

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYMediaPlayer_Android#32]

**Comment by FirmianaRain** [comment]
这个接口只对软解有效
这个接口应该与Android系统版本无关，可否提供更多的信息，比如测试机型及其他

**Comment by Goach** [comment]
那硬解码的话，得到的就是黑屏的画面吗，我用的是联想L50-T5 ,Samsung GT-N7100都会这样

**Comment by Goach** [comment]
怎么才知道使用的软解码还是硬解码

**Comment by FirmianaRain** [comment]
使用硬解时，播放器拿不到解码之后的数据，在硬解情况下截图就是全黑的
SDK默认使用  **软解**，只有在设置使用硬解后，SDK才会使用硬解，SDK提供的硬解接口可参见：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/hardwareDecode

**Comment by Goach** [comment]
里面说的是尝试使用硬解码，那怎么才能知道该手机在白名单里面硬解码尝试成功没切换为软解码呢，

**Comment by FirmianaRain** [comment]
从Android版本v1.4.6起，在onInfo回调中会告知当前是使用的是：硬解or软解
对应字段为：MEDIA_INFO_HARDWARE_DECODE 和 MEDIA_INFO_SOFTWARE_DECODE
具体消息定义与错误码定义可参见：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KsyMediaPlayerConstants

**Comment by Goach** [comment]
好的，谢谢了，
