### ISSUE TITLE
部分手机Reload直播会黑屏

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYMediaPlayer_Android#34]
motorola XT1079 测试会出现这个问题，使用的版本是1.5.2，ksyMediaPlayer.reload(mDataSource,true);

**Comment by FirmianaRain** [comment]
可以使用: reload(url, true, KSYReloadMode. KSY_RELOAD_MODE_ACCURATE)
具体可见：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/reload

**Comment by Goach** [comment]
设置KSY_RELOAD_MODE_ACCURATE和KSY_RELOAD_MODE_FAST都会出现，是在我们分享直播成功后回来的重新reset就会有这个问题，我这边已经得到了reset成功的返回值，但是就是黑屏

**Comment by FirmianaRain** [comment]
请问使用的是硬解or软解？

**Comment by Goach** [comment]
用一个硬解手机测试会出现
com.hoomic.forums D/zgx: SurfaceViewActivity.java(312) onInfo: MediaPlayer==========onInfo==i:10001,i1:0
09-22 20:24:00.667 23116-23116/com.hoomic.forums D/zgx: SurfaceViewActivity.java(312) onInfo: MediaPlayer==========onInfo==i:41000,i1:0
09-22 20:24:00.668 23116-23116/com.hoomic.forums D/zgx: SurfaceViewActivity.java(312) onInfo: MediaPlayer==========onInfo==i:50001,i1:0




![screenshot_2016-09-22-20-26-21](https://cloud.githubusercontent.com/assets/13835896/18748222/d5a6b584-8103-11e6-8591-3bc824ee72e0.png)

**Comment by FirmianaRain** [comment]
请问reset之后有设置新的  Surface或者SurfaceHolder吗？
具体可参考: https://github.com/ksvc/KSYMediaPlayer_Android/wiki/reconnectAndRestart

**Comment by Goach** [comment]
我使用的是TextureView，只能用reload方法吧，我用的是1.5.3版本的，reload方法if(ksyMediaPlayer != null)
            ksyMediaPlayer.reload(mDataSource,true);

**Comment by Goach** [comment]
现在发现不是reload的原因，原因是只要 mVideoTextureView.isAvailable()返回true，就无法setSurfaceTexture，导致硬解码的手机back的时候黑屏，使用最新的KSYTextureView也是一样的效果，
 @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    public void reinitTextureView(KSYTextureView view) {
        mVideoTextureView = view;
        mVideoTextureView.setSurfaceTextureListener(this);
        //需要检测Texture是否是available，否则在某些设备上会引起崩溃
        if (!mVideoTextureView.isAvailable()) {
            if (mSurfaceTexture != null) {
                mVideoTextureView.setSurfaceTexture(mSurfaceTexture);
            }
        }
    }

**Comment by FirmianaRain** [comment]
请参见KSYTextureView的介绍：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KSYTextureView
在KSYTextureView内部已经设置SurfaceTextureListener，不建议用户设置该监听器

**Comment by Goach** [comment]
现在已换成最新的KSYTextureView了，也是一样的效果。其他的back不会黑屏，就是启动第三方分享后back会黑屏。

**Comment by FirmianaRain** [comment]
前后台切换和第三方分享，对于SDK来说没有区别
请看下在启动三方分享后切回前台，是否有调用runInForeground这个接口

**Comment by Goach** [comment]
runInForeground肯定会执行 ，关键就是isAvailable返回为true，而其他back返回的是false

**Comment by FirmianaRain** [comment]
请不要调用mVideoTextureView.setSurfaceTextureListener(this)，在KSYTextureView内部已经设置了相应的监听器
也不要调用mVideoTextureView.setSurfaceTexture(mSurfaceTexture)
在前后台切换时，请在适当时机调用runInBackground和runInForeground即可

**Comment by Goach** [comment]
已调试过，确定没有调用setSurfaceTextureListener和setSurfaceTexture了，runInBackground和runInForeground也已经正常运行，唯一不同的是我上面说的isAvailable返回值不同了，我查官网上说的是Returns true if the SurfaceTexture associated with this TextureView is available for rendering. When this method returns true, getSurfaceTexture() returns a valid surface texture.
是不是因为我分享操作时，isAvailable返回为true，getSurfaceTexture已经无效，所以获取不到数据，以致黑屏，back的时候声音是有的，求请教isAvailable。

**Comment by FirmianaRain** [comment]
我们这边会先尝试复现这个问题的
可否提供下测试机型的信息，比如机型，Android版本等
可否提供下大致的操作步骤

**Comment by ruoshuisanqian** [comment]
我也遇到一样的问题，从后台回来就必须要立即调用runInForeground方法 否则会黑屏，但是手动暂停的时候，我希望可以手动恢复播放。

**Comment by Goach** [comment]
你是在哪里调用的runInForeground，能具体说下你的解决办法吗？我是在onResume里面调用的，调试他back回来会去执行runInForeground。但是我的还是黑屏。

**Comment by FirmianaRain** [comment]
@ruoshuisanqian 你的需求是在切回前台时调用runInForeground不会立刻开播吗？可以由你掌控什么时候开播？

**Comment by ruoshuisanqian** [comment]
@FirmianaRain 是的

**Comment by FirmianaRain** [comment]
@ruoshuisanqian 这个可能得下周才能做了

**Comment by wshichang** [comment]
@Goach 硬解黑屏能否提供下，复现设备型号以及andorid版本号？

**Comment by Goach** [comment]
使用的是Android5.0，硬解码手机都行，Android Studio2.2，分享使用的是第三方友盟分享。只要点击分享到任意平台，取消分享回来，或者分享成功返回，就会出现TextureView.isAvailable返回为true，从而黑屏。

**Comment by Goach** [comment]
请问下，你们这边现在重现出来过这个bug吗？

**Comment by FirmianaRain** [comment]
这个bug已经复现了
预计这周三上线的版本可以修复此问题

**Comment by Goach** [comment]
今天提交的已经修复了这个bug吗？修复了的话，哪里需要调整吗，还是直接替换SDK就行了。我这边升级了还是会黑屏

**Comment by FirmianaRain** [comment]
https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KSYTextureView
请看文档中 **注意事项** 的相关介绍

**Comment by Goach** [comment]
好了，谢谢了，只是现在刚回来的时候偶尔会花屏一下

**Comment by FirmianaRain** [comment]
用的是硬解吧？
分享和前后台切换对TextureView的影响不太一样，导致这个问题的出现。
后续我们会继续优化，彻底解决这个问题

**Comment by Goach** [comment]
是的，软解一直都是没问题的。好的，
