### ISSUE TITLE
bug 日志

### ISSUE THREAD

**Issue by Goach** [ksvc/KSYMediaPlayer_Android#35]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x40740ad0 in tid 19708 (Thread-68824)
09-22 18:26:35.067 22943-22943/com.hoomic.forums E/KSYMediaPlayer: SDL_VoutAndroid_setVideoScalingMode_l: NULL NativeWindow
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6764001e
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: acb40f03
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6fcb0800
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00030008
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000300
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: f078b175
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:26:36.737 22943-23086/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 68ef3cb0
09-22 18:26:47.231 22943-23024/com.hoomic.forums A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7ad70448 in tid 23024 (Thread-68782)
09-22 18:26:51.633 23545-23545/com.hoomic.forums E/KSYMediaPlayer: SDL_VoutAndroid_setVideoScalingMode_l: NULL NativeWindow
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6764001e
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: acb40f03
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6fcb0800
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00030008
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000300
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: f078b175
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:27:15.923 23545-23680/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 68ef3cb0
09-22 18:27:26.839 23545-23545/com.hoomic.forums E/com.ksyun.media.player.KSYMediaPlayer: Error (-1004,0)
09-22 18:27:26.954 23545-24244/com.hoomic.forums E/KSYMediaPlayer: [zzy]MediaCodec meet an error
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6764001e
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: acb40f03
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6fcb0800
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00030008
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000300
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: f078b175
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:27:27.867 23545-24493/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 68ef3cb0
09-22 18:29:19.256 23545-23731/com.hoomic.forums A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x2c80dd6b in tid 23731 (pool-15-thread-)
09-22 18:29:23.579 27133-27133/com.hoomic.forums E/KSYMediaPlayer: SDL_VoutAndroid_setVideoScalingMode_l: NULL NativeWindow
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6764001e
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: acb40f03
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 6fcb0800
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00030008
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000300
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: f078b175
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 00000001
09-22 18:29:29.236 27133-27283/com.hoomic.forums E/KSYMediaPlayer: csd-0[36]: 68ef3cb0

**Comment by Goach** [comment]
播着播着保错

NativeCrashListener: Exception dealing with report
                                                     android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                         at libcore.io.Posix.readBytes(Native Method)
                                                         at libcore.io.Posix.read(Posix.java:147)
                                                         at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                         at android.system.Os.read(Os.java:364)
                                                         at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                         at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)

**Comment by FirmianaRain** [comment]
这是硬解相关的日志，并不能看出具体的问题

**Comment by Goach** [comment]
用最新版本1.5.3就不会出现这个问题了

**Comment by mrcoolbiz** [comment]
I got same issue. 
I can hear the sound but not video.
