### ISSUE TITLE
Unknown verification type [18] in stack map frame问题

### ISSUE THREAD

**Issue by xiangyutian** [ksvc/KSYMediaPlayer_Android#37]
描述：
更新了1.5.4版本库；编译正常；但是在连接真机安装时，报错，log如下：
(Can't process class [com/ksyun/media/player/https/b$1.class] (Unknown verification type [18] in stack map frame))；
google一下，大概意思是混淆问题，但是我目前是调试debug版本；请问还会是别的什么问题？

**Comment by xiangyutian** [comment]
大致是混淆jar时出现了问题，不知道金山这边打包的脚本是否也是自动化编译和混淆，查到了类似资料供参考：http://blog.csdn.net/jiguangcanhen/article/details/41806599

**Comment by FirmianaRain** [comment]
我这用小米4，Android版本6.0.1，用demo做测试，未能复现你的问题。
其中Android Studio用的build tools version是24.0.0

**Comment by xiangyutian** [comment]
回滚到1.5.3版本的jar包，就正常了；

**Comment by FirmianaRain** [comment]
QA以及RD用1.5.4的包做测试都没遇到与你类似的问题，不知可否提供更详细的信息
比如，用的真机的相关信息，Android Studio的build tools版本等

**Comment by xiangyutian** [comment]
IDE: studio2.2正式版；
compileSdkVersion 23
buildToolsVersion '23.0.3'
targetSdkVersion 23

ide环境里clean和rebuild都能正常通过，不会报错，但是在run到真机时，报了Error:Execution failed for task ':MiXiongVideo:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't read [/Users/MiXiongVideo/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar] (Can't process class [com/ksyun/media/player/https/b$1.class] (Unknown verification type [18] in stack map frame))

**Comment by FirmianaRain** [comment]
请问是否有对player的jar做混淆呢？

**Comment by xiangyutian** [comment]
抱歉，回复晚了。是这样的，我在debug下安装就提示了上述错误，在debug下是没有任何混淆逻辑的；

**Comment by xiangyutian** [comment]
应该和https://github.com/ksvc/KSYMediaPlayer_Android/issues/38 是一个问题引起的；

**Comment by wshichang** [comment]
已经做了修改请更新
