### ISSUE TITLE
1.5.1调试正常，发布APK会提示错误

### ISSUE THREAD

**Issue by zllikey** [ksvc/KSYMediaPlayer_Android#38]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't read [D:\Tool\AndroidStudioProjects\newplay\app\libs\libksyplayer.jar(;;;;;;**.class)] (Can't process class [com/ksyun/media/player/https/b$1.class] (Unknown verification type [18] in stack map frame))

**Comment by FirmianaRain** [comment]
能否提供下你所使用的编译环境的信息呢？
比如，java版本，Android studio版本，build tools的版本等版本信息

**Comment by zllikey** [comment]
Java SE Development Kit 8 64-bit   Android studio版本2.2 

    compileSdkVersion 24
    buildToolsVersion '24.0.1'
    defaultConfig {
        minSdkVersion 14
        versionCode 26
        versionName "2.1.7"

**Comment by FirmianaRain** [comment]
是在Windows上出现这种问题的吗

**Comment by zllikey** [comment]
恩，是的.,WINDOWS,是个别案例吗？

**Comment by zllikey** [comment]
对了，我开启了混肴，关了就正常了，我的规则 
#金山云播放器
-dontwarn com.ksyun.media.player.*
-keep class com.ksyun.media.player.** { *; }

以前可以，现在不行了

**Comment by wshichang** [comment]
已经做了修改请更新
