### ISSUE TITLE
用金山云播放器播放一段时间视频后自动退出播放

### ISSUE THREAD

**Issue by shawtimxiaotian** [ksvc/KSYMediaPlayer_Android#57]
问题现象：集成金山云播放器开源1.6.8版本的app在播放视频时，时长几分钟到十分钟左右不等，自动退出播放，用播放器sdk中的demo播放，也自动退出播放。
平台：Android
机型：360 n4s（联发科版），HUAWEI G700-U00，荣耀畅玩4x标配版，三星pad GT-N5100，小米pad2
步骤：进入到app的影视页面，随意选择一个媒资进行播放,然后观察现象
补充：用Android studio进行调试,自动退出播放时触发onError，随后触发onComplete（这两个事件均是标准播放事件，onError表示存在不可忽略错误，onComplete表示当前视频播放完成）。其中onError报的是（1，0），按金山云定义，1表示MEDIA_ERROR_UNKNOWN，即未知错误。如果强行忽略，视频直接卡住静帧，任何操作均会再次触发onComplete），我这边可提供app和播放串配合金山云进行测试。

**Comment by FirmianaRain** [comment]
不知能否提供下播放地址

**Comment by shawtimxiaotian** [comment]
@FirmianaRain 这个播放串：http://ott1.ysbn.cn:8088/vod/thgq,16102716335900158843.m3u8?fmt=x264_7500k_mpegts&sora=1&timecode=0&sk=5136DB59C31D650FAFC69E06296BDD7B&uuid=fef0b3de-5e1b-456b-892c-08b96dfd226d&userCode=15271898135&userName=15271898135&spCode=484581254562&productCode=6501220&resourceCode=102443838&subId=17213688&resourceName=&authType=2

**Comment by FirmianaRain** [comment]
好的，多谢，我们会尽快分析下问题

**Comment by shawtimxiaotian** [comment]
@FirmianaRain 你好，请问下有什进展没有？是流的问题还是播放器的问题？

**Comment by wshichang** [comment]
我这里复现了几次，都是长时间读不到数据，触发超时了

**Comment by shawtimxiaotian** [comment]
@wshichang 是长时间请求不到视频流吗？

**Comment by wshichang** [comment]
@shawtimxiaotian 是的，http很长时间读不到数据，然后就超时了

**Comment by shawtimxiaotian** [comment]
@wshichang 这个问题是我换了新版本的金山云播放器才出现的，之前用去年八九月份开源版本的金山云播放器没出现这个问题，现在用老版本的金山云播放器测，还是没出现退出播放的情况

**Comment by wshichang** [comment]
@shawtimxiaotian  真的吗版本是多少？

**Comment by shawtimxiaotian** [comment]
@wshichang 不知道版本号，只知道包名叫com.ksy.media.player，去年八九月份开源的，后来被你们给闭源了，github地址是这个https://github.com/ks3sdk。另外问你一个问题，新金山云播放器在请求视频流超时后没有重复请求播放地址的机制吗？就直接报错？

**Comment by FirmianaRain** [comment]
那是把上层的部分代码开源了，但是底层播放一直是以SDK的形式提供
