### ISSUE TITLE
KSYTextureView播放停止后无法再次播放

### ISSUE THREAD

**Issue by BDwuzhou** [ksvc/KSYMediaPlayer_Android#64]
用KSYTextureView播放rtmp流，当直播流中断时，播放器停止，此时reset并且重新初始化无效；
当主动reset播放器并release时，再次初始化同样无效，请问如何解决

**Comment by FirmianaRain** [comment]
reset之后需要重新调用prepareAsync，再走一次开播的逻辑
release是退出Activity时调用，释放播放器

**Comment by BDwuzhou** [comment]
重新走一次播放的逻辑也是一样的

**Comment by FirmianaRain** [comment]
大致流程应该如下：
1. reset
2. setDataSource
3. prepareAsync
4. 收到onPrepared回调，开始播放视频
如果确认以上以上接口都被调用的情况下，还是无法播放视频，那么请再确认：
1. 该视频可被其他播放器播放的

**Comment by BDwuzhou** [comment]
确认以上接口全部调用，并且视频可以被ffplay播放，reset前后播放的视频是同一个流，只不过是切断之后重新推

**Comment by wshichang** [comment]
@BDwuzhou 我用demo是这样操作的，在onerror中调用reset();setDataSource(mDataSource);prepareAsync(); 然后开始测试，用一个设备开始推流另一个播放这路流，播放成功后点击停止直播，过一段时间后再点击开始直播。播放端可以正常播放没有复现你说的问题。
