### ISSUE TITLE
请问播放网络视频能否边下边播？

### ISSUE THREAD

**Issue by xwlcn** [ksvc/KSYMediaPlayer_Android#70]
我在播放网络视频的时候想边下载边播放，但是好像没有看到类似的方法来设置。只看到了一个用来设置缓存buffer大小和buffer time的，不知道官方有没有这样的功能？如果没有的话，是否考虑以后加上这个功能呢？

**Comment by fpzeng** [comment]
https://github.com/ksvc/ksyhttpcache_android
边下载边播放，请配合ksyhttpcache_android组件实现。播放器内未内建该功能

**Comment by xwlcn** [comment]
谢谢。
