### ISSUE TITLE
普通M3U8 MP4 硬解什么时候才能实现

### ISSUE THREAD

**Issue by zllikey** [ksvc/KSYMediaPlayer_Android#9]
普通M3U8 MP4 硬解什么时候才能实现，好期待吖

**Comment by FirmianaRain** [comment]
已经支持硬解了
最终是否是硬解关键看机型，而不是视频的文件格式

**Comment by zllikey** [comment]
是你们指定的机型吗？能否告知？

**Comment by FirmianaRain** [comment]
比较典型的机型是小米4、5，三星S6

**Comment by timliu123123** [comment]
如果用在APK上，硬件解码不现实，用户有好多低端机器，而H265的花屏问题，太讨厌了，能否先解决下软解码H265的花屏问题？

**Comment by timliu123123** [comment]
HLS状态下1个30分钟的视频出现1~2次的花屏，H265解码。

**Comment by FirmianaRain** [comment]
请问用的什么版本？
HLS播放地址是什么？

**Comment by timliu123123** [comment]
用的库是最新的1.4.2的，视频播放地址：
http://video.ewt360.com:8080/hls-vod/ewt360/kkxy/lbkc/zhangheqiang/9.07zhq01.f4v.m3u8

这个地址反复播放，就会出问题，我们用的手机小米3

**Comment by timliu123123** [comment]
这样的，用H264的格式播放的时候，按home键再进去会出现很长时间的黑屏和花屏，所以选择H265的格式播放，多试几次，再不同网络环境下，一定存在花屏问题的，后面出现了，我切屏发过来。
