### ISSUE TITLE
如何知道視頻已經 Prepared 了？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYMediaPlayer_Android#92]
再已經執行過 `ksyMediaPlayer.prepareAsync();` 想在 onPreparedListener 以外的地方知道視頻目前狀態，有辦法知道影片是否 Prepared 了嗎？

**Comment by FirmianaRain** [comment]
现在只能在 onPreparedListener 监听到 onPrepared的回调，也即视频已经prepared的消息
