### ISSUE TITLE
暫停和停止的區別？

### ISSUE THREAD

**Issue by bingdow** [ksvc/KSYMediaPlayer_Android#93]
目前發現 pause 後再調用 start 方法及可繼續播放，而 stop 以後用 start 則無效果，請問 stop 後要如何繼續播放？
另一個問題是，我希望重新播放推流時從最新的片段開始，而不是從上次暫停/停止的地方，具體該怎麼實現？

**Comment by FirmianaRain** [comment]
1. pause只是让播放器暂停，是状态的变化，start之后还能继续播放；stop会关闭播放器的内部线程，调用start之后不能继续播放

**Comment by samuelg78** [comment]
请问我是直播视频， 我已参考https://github.com/ksvc/KSYMediaPlayer_Android/wiki/reconnectAndRestart。不推荐使用pause, 所以我stop在onPaused event. 之后用以下， 却有info: MEDIA_INFO_SOFTWARE_DECODE, 如何解决？

private void RestartVideoPlayer() {
       try {
            mVideoView.reset();
            mVideoView.setDataSource(mDataSource);
            mVideoView.prepareAsync();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

**Comment by FirmianaRain** [comment]
1. 硬解建议使用KSYTextureView，具体可看wiki：https://github.com/ksvc/KSYMediaPlayer_Android/wiki/KSYTextureView，3.7节讲解了前后台切换时可具体的调用方法
2. reset之后所有的参数和设置都需要重新设置一次
